name = "Memoize"
uuid = "0fb7230c-a6dd-11e8-35c5-25eda89965fd"
authors = ["Simon Kornblith <simon@simonster.com>"]
version = "0.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
